name: Build OpenHands Runtime with AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::839695154978:role/openhands-runtime-role
          aws-region: ap-northeast-1

      - name: Get AWS credentials from SSM Parameter Store
        run: |
          # SSMパラメータの存在を確認
          if aws ssm describe-parameters --parameter-filters "Key=Name,Values=parameter-reader-access-key-id" --query "Parameters[*].Name" --output text | grep -q "parameter-reader-access-key-id"; then
            echo "SSM parameter parameter-reader-access-key-id exists"
            AWS_ACCESS_KEY_ID=$(aws ssm get-parameter --name parameter-reader-access-key-id --with-decryption --query Parameter.Value --output text)
            echo "::add-mask::$AWS_ACCESS_KEY_ID"
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          else
            echo "Error: SSM parameter parameter-reader-access-key-id does not exist"
            exit 1
          fi
          
          if aws ssm describe-parameters --parameter-filters "Key=Name,Values=parameter-reader-secret-access-key" --query "Parameters[*].Name" --output text | grep -q "parameter-reader-secret-access-key"; then
            echo "SSM parameter parameter-reader-secret-access-key exists"
            AWS_SECRET_ACCESS_KEY=$(aws ssm get-parameter --name parameter-reader-secret-access-key --with-decryption --query Parameter.Value --output text)
            echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          else
            echo "Error: SSM parameter parameter-reader-secret-access-key does not exist"
            exit 1
          fi
          
          echo "AWS_REGION=ap-northeast-1" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 839695154978.dkr.ecr.ap-northeast-1.amazonaws.com/openhands-runtime:${{ github.sha }}
          build-args: |
            AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ env.AWS_REGION }} 